apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: xnjh
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: xnjh
    app.kubernetes.io/part-of: byoc-app-pbrv
  name: xnjh
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: xnjh
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: xnjh
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/byoc-twrn-tenant/byoc-app-pbrv/xnjh@sha256:4417cc36b6d592351094bf10b16adb86448a7fcfeb09580c11ec4bc4a3d226b3
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
