apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: xnjh
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: xnjh
    app.kubernetes.io/part-of: byoc-app-pbrv
  name: xnjh
spec:
  rules:
  - host: xnjh-byoc-twrn-tenant.apps.ed3a7521f5359cfb3322.hypershift.aws-2.ci.openshift.org
    http:
      paths:
      - backend:
          service:
            name: xnjh
            port:
              number: 8081
        path: /
        pathType: ImplementationSpecific
status:
  loadBalancer: {}
